### ISSUE TITLE
player is invisible in gtnh2.6.0  GTNH2.6.0beta2中玩家实体不可见

### ISSUE THREAD

**Issue by txzzqaz** [wohaopa/ReplayModFixMod#5]
i dont know if someone still here,but as the title,player is invisible in record file
我不知道是否有人仍在维护这个项目，但是正如标题所说，GTNH2.6.0beta2中玩家实体在replay viewer中不可见，但是其他生物和烟花正常，其他的没有测试。

**Comment by wohaopa** [comment]
See https://github.com/wohaopa/ReplayModFixMod/issues/4
This is a known bug due to ReplayMod itself. This bug seems to be able to fix itself after entering the replay center for the third time after starting the game.
And I don't have time to fix it now and in the next year.

This is a Chinese translation:
这是一个已知的bug，因为ReplayMod本身的原因。这个bug似乎会在每一次启动游戏后的第三次进入回放中心后自行消除。
并且，我现在与接下来的一年内没有时间修复它。
